variables:
    FACTORY_PRODUCT_NAME: import
    FACTORY_PACKAGE_TYPE: module

stages:
- release

tickets:
  stage: release
  only:
    - tags
  image:
    name: $REGISTRY_URI/infra/ci-tools:latest
  script:
    - create_ticket.py
  tags:
    - factory-plain

gitlab_release:
  stage: release
  rules:
      - if: '$CI_COMMIT_TAG =~ /^\d{4}\.\d{2}\.\d{2}$/'
        # Running only when the tag is like YYYY.MM.DD
        when: always
      - when: never
  image:
    name: $REGISTRY_URI/infra/ci-tools:latest
  script:
    - gitlab_release
  tags:
    - factory-plain
