name: Tests 🎳

on:
  push:
    tags:
      - '*'
    branches:
      - '*'
  pull_request:

jobs:
  release:
    name: Create Release
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/')

    steps:

      - name: Set env
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

      - uses: actions/checkout@v4

      - name: Read the changelog
        id: changelog
        uses: 3liz/changelog-release@0.2.1
        with:
          tag_name: ${{ env.RELEASE_VERSION }}

      - name: Create release on GitHub
        uses: ncipollo/release-action@v1.16.0
        with:
          body: ${{ steps.changelog.outputs.markdown }}
          token: ${{ secrets.BOT_HUB_TOKEN }}
